###

GET http://localhost:3000/post

###

GET http://localhost:3000/post?owner=elad

###

GET http://localhost:3000/post/6758c8e84540428283cbdff9

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Hello",
    "content": "Hello World...",
    "owner": "elad"
    
}

###

DELETE http://localhost:3000/post/6758c8e84540428283cbdff9
###

PUT http://localhost:3000/post/6758c8e84540428283cbdff9
Content-Type: application/json

{
    "title": "Hello",
    "content": "Hello World...",
    "owner": "aniiiiiiii"
    
}

###

GET http://localhost:3000/comment

###

GET http://localhost:3000/comment?owner=elad

###

GET http://localhost:3000/comment/6758c94b4540428283cbe005

###

PUT http://localhost:3000/comment/6758c96c4540428283cbe008
Content-Type: application/json

{
    "title": "hear me out",
    "content": "i agree with that",
    "postId": "6758c94b4540428283cbe005",
    "owner": "roi"
    
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "title": "hear me out",
    "content": "i dont agree with that at all",
    "postId": "6758c94b4540428283cbe005",
    "owner": "elad"
    
}

###

DELETE http://localhost:3000/comment/6758c9814540428283cbe00a



