###

GET http://localhost:3000/post

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@user.com",
    "password": "testPassword"
    }


###

GET http://localhost:3000/post?owner=Kevin

###

GET http://localhost:3000/post/673d1bb3c99fa652ad948d8f

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Hello",
    "content": "Hello World...",
    "owner": "ani"
    
}

###

DELETE http://localhost:3000/post/67574579beea74975307c4ff
###

PUT http://localhost:3000/post/674dd075aeda9c8ab783ca39
Content-Type: application/json

{
    "title": "Hello",
    "content": "Hello World...",
    "owner": "aniiiiiiii"
    
}

###

GET http://localhost:3000/comment

###

GET http://localhost:3000/comment?owner=elad

###

GET http://localhost:3000/comment/674dd075aeda9c8ab783ca39

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "title": "hear me out",
    "content": "i dont agree with that at all",
    "postId": "674dd075aeda9c8ab783ca39",
    "owner": "me"
    
}

###

DELETE http://localhost:3000/comment/674da298471486216fd8c213